### ISSUE TITLE
NO_WRITE_SESSION and --no-write-session do not work

### ISSUE THREAD

**Issue by debonet** [duanemay/chatgpt-cli#1]
The flag `--no-write-session` causes an error:

~~~bash
bash-3.2$ chatgpt-cli --no-write-session chat
Error: unknown flag: --no-write-session
~~~

and the config parameter `NO_WRITE_SESSION` has no effect

~~~
NO_WRITE_SESSION=true
~~~

**Comment by duanemay** [comment]
@debonet, Thank you for pointing this out. 
The flag had been renamed to `--skip-write-session` to avoid confusion around the negative with true/false. 
I missed the README file when making this change earlier. It has now been updated, and I added an example to clarify the prefix on the environment variables as well.

Proper use is:
`--skip-write-session` on the command line
`SKIP_WRITE_SESSION` in a config file, and
`CHATGPT_SKIP_WRITE_SESSION` for an environment variable.
